---
# file: project/apache2.yml

- hosts: apache2
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/apache2"
    - debug: var=fact_role_path

  roles:

    - apache2
